In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
env = gym.make("FrozenLake-v0")

In [0]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
action_space_size

4

In [5]:
state_space_size

16

In [6]:
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.003

In [8]:
rewards_all_episodes = []
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
      # Exploration-exploitation trade-off
      exploration_rate_threshold = random.uniform(0, 1)
      if exploration_rate_threshold > exploration_rate:
          action = np.argmax(q_table[state,:]) 
      else:
          action = env.action_space.sample()  

      new_state, reward, done, info = env.step(action)
      # Update Q-table for Q(s,a)
      q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
          learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))  

      state = new_state
      rewards_current_episode += reward   
      if done == True: 
        break
        
        # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
        # Exploration rate decay   
        # Add current episode reward to total rewards list

# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
  print(count, ": ", str(sum(r/1000)))
  count += 1000

# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.16800000000000012
2000 :  0.5720000000000004
3000 :  0.6380000000000005
4000 :  0.6760000000000005
5000 :  0.6680000000000005
6000 :  0.6730000000000005
7000 :  0.6610000000000005
8000 :  0.7000000000000005
9000 :  0.6770000000000005
10000 :  0.6810000000000005


********Q-table********

[[5.92935387e-01 5.07410159e-01 4.92562340e-01 5.02919125e-01]
 [9.53219518e-02 1.99608655e-01 1.52489411e-01 4.58574183e-01]
 [3.99436227e-01 1.88422971e-01 1.45887432e-01 1.91959252e-01]
 [4.71570386e-04 2.97651564e-02 1.25986806e-04 2.04889412e-04]
 [6.07517675e-01 2.61300665e-01 3.41843260e-01 3.66578731e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.53271036e-01 1.15690596e-01 3.13659218e-01 8.92018950e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.84890257e-01 4.12905642e-01 3.09332989e-01 6.47350123e-01]
 [3.71619177e-01 7.26103082e-01 4.49759541e-01 4.89629003e-01]
 [7.40401038e-01 

In [9]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
              
        if done:
          clear_output(wait=True)
          env.render()
          if reward == 1:
              print("****You reached the goal!****")
              time.sleep(3)
          else:
              print("****You fell through a hole!****")
              time.sleep(3)
              clear_output(wait=True)
          break   
        state = new_state     
            
        # Set new state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
